### ISSUE TITLE
PASSWORD_DEFAULT undefined

### ISSUE THREAD

**Issue by cxj** [aretecode/Todo#1]
Notice: Use of undefined constant PASSWORD_DEFAULT - assumed 'PASSWORD_DEFAULT' in /todo/web/login.php on line 35

Warning: hash(): Unknown hashing algorithm: PASSWORD_DEFAULT in /todo/vendor/aura/auth/src/Verifier/PasswordVerifier.php on line 59

**Comment by aretecode** [comment]
What version of PHP are you using? 
http://php.net/manual/en/password.constants.php
http://php.net/manual/en/function.password-hash.php

**Comment by cxj** [comment]
Ack!  Sorry.  CLI was PHP 5.6, but I missed configuring Apache correctly, which was still using PHP 5.4.
