### ISSUE TITLE
Functional?

### ISSUE THREAD

**Issue by cxj** [aretecode/Todo#2]
I've not been able to get this to work.  Using the PHP web server as described in the README fails in a number of ways, especially in the index.php references to REDIRECT_URL which only exists (as far as I can tell) when Apache is used as the web server.

If I run it from within an Apache virtual host, the AJAX calls seem to go off into never-never land.  The Apache server never sees/logs the requests at all.  They seem to be wrongly trying to connect to port 8080, for one.

What I really wanted to do was learn from this example, enough to create some way of using Twig as my responder's body filter.  Paul's Radar is a bit cryptic; I was hoping you'd solved that problem and I could understand how you did it.

**Comment by cxj** [comment]
Looks like the Apache problem is in web/ajax.php with this hard-coded line:

``` javascript
      var url = "http://localhost:8080/todo";
```

**Comment by aretecode** [comment]
Did you manage to make it run? I did not have luck using AJAX on a non local server. 
Did the non AJAX version in /tests/index.php work for you?
Different HTTP methods had interesting issues in the Responder that seemed to be in the Zend package.

**Comment by cxj** [comment]
I changed the above mentioned line to code it for my Apache host.  It then seemed to work fine as far as I tested it, running under Apache.  I did not try the non-AJAX tests.
